/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.karim.main.composant;

import com.karimandco.auth.PanneauFormInscription;
import fr.karim.main.utils.Helpers;
import fr.karim.main.utils.user.Utilisateur;
import fr.karim.references.Reference;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;

/**
 *
 * @author karim
 */
public class Inscription extends javax.swing.JPanel {

    /**
     * Creates new form Inscription
     */
    public Inscription() {
        initComponents();
        panneauFormInscription1.setOpaque(true);
        panneauFormInscription1.setBackground(Reference.MAIN_DARK);
        this.setBackground(Reference.MAIN_DARK);
        
        jScrollPane1.setOpaque(true);
        jScrollPane1.setBackground(new Color(0,0,0,0));
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelTitleAPI = new javax.swing.JLabel();
        jPanelAuthWithAPI1 = new fr.karim.main.auth.JPanelAuthWithAPI();
        jScrollPane1 = new javax.swing.JScrollPane();
        panneauFormInscription1 = new com.karimandco.auth.PanneauFormInscription();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jLabelTitle.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("S'inscrire");

        jLabelTitleAPI.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelTitleAPI.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitleAPI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleAPI.setText("S'inscrire Facebook ou Google");

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportView(panneauFormInscription1);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jSeparator2)
                .addComponent(jPanelAuthWithAPI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTitleAPI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelTitleAPI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAuthWithAPI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    public void initialize(){
        
        jLabelTitle.setText(Utilisateur.getInstance().getEstConnecte() ? "Modification du compte" : "Inscription");
        if(Utilisateur.getInstance().getEstConnecte()){
            jLabelTitleAPI.setVisible(false);
            jPanelAuthWithAPI1.setVisible(false);
        }
        
        jPanelAuthWithAPI1.getjPanelFacebook1().getjButtonOAuth().addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                
                panneauFormInscription1.getPanneauNom().getChamp2().setText(jPanelAuthWithAPI1.getUserOAuthFacebook().getFirstName());
                panneauFormInscription1.getPanneauPrenom().getChamp2().setText(jPanelAuthWithAPI1.getUserOAuthFacebook().getLastName());
                panneauFormInscription1.getPanneauCourriel().getChamp2().setText(jPanelAuthWithAPI1.getUserOAuthFacebook().getEmail());
                
                SimpleDateFormat simpleDateFormat = new SimpleDateFormat("mm/dd/yyyy");

                try {
                    Date date = simpleDateFormat.parse(jPanelAuthWithAPI1.getUserOAuthFacebook().getBirthday());
                    String dateString = new SimpleDateFormat("dd/MM/yyyy").format( date );
                    panneauFormInscription1.getPanneauDateNaissance().getChamp2().setText(dateString);

                } catch (ParseException ex) {
                    Logger.getLogger(Inscription.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                panneauFormInscription1.getPanneauIdentifiant().getChamp2().setText(jPanelAuthWithAPI1.getUserOAuthFacebook().getShortName().replace(" ", ""));
            }

            @Override
            public void mousePressed(MouseEvent e) { }

            @Override
            public void mouseReleased(MouseEvent e) { }

            @Override
            public void mouseEntered(MouseEvent e) { }

            @Override
            public void mouseExited(MouseEvent e) { }
        });
        
        jPanelAuthWithAPI1.getjPanelGoogle1().getjButtonOAuth().addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {

                panneauFormInscription1.getPanneauNom().getChamp2().setText(jPanelAuthWithAPI1.getUserOAuthGoogle().getFamily_name());
                panneauFormInscription1.getPanneauPrenom().getChamp2().setText(jPanelAuthWithAPI1.getUserOAuthGoogle().getGiven_name());
                panneauFormInscription1.getPanneauCourriel().getChamp2().setText(jPanelAuthWithAPI1.getUserOAuthGoogle().getEmail());
                
                // voir pour la date de naissance avec l'api google
                // panneauFormInscription1.getPanneauDateNaissance().getChamp2().setText(jPanelAuthWithAPI1.getUserOAuthGoogle().getBirthday());
                
                panneauFormInscription1.getPanneauIdentifiant().getChamp2().setText(jPanelAuthWithAPI1.getUserOAuthGoogle().getName().replace(" ", ""));
            }

            @Override
            public void mousePressed(MouseEvent e) { }

            @Override
            public void mouseReleased(MouseEvent e) { }

            @Override
            public void mouseEntered(MouseEvent e) { }

            @Override
            public void mouseExited(MouseEvent e) { }
        });

        panneauFormInscription1.getjButtonInscription().addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) { 
                if(!panneauFormInscription1.getIdentifiantOK()){
                    JOptionPane.showMessageDialog(jScrollPane1, "Attention ! Cette identifiant est déjà utiliser.", "Identifiant invalide", JOptionPane.WARNING_MESSAGE);
                } 
                if(!panneauFormInscription1.getIdentifiantOK()){
                    JOptionPane.showMessageDialog(jScrollPane1, "Attention ! Cette email est déjà utiliser.", "Email invalide", JOptionPane.WARNING_MESSAGE);
                } 
            }

            @Override
            public void mousePressed(MouseEvent e) { }

            @Override
            public void mouseReleased(MouseEvent e) { }

            @Override
            public void mouseEntered(MouseEvent e) { }

            @Override
            public void mouseExited(MouseEvent e) { }
        });
        
        panneauFormInscription1.getPanneauIdentifiant().getChamp2().getDocument().addDocumentListener(new Helpers.SimpleDocumentListener() {
            @Override
            public void update(DocumentEvent e) {
                checkIdentifiant();
            }
        });
        
        panneauFormInscription1.getPanneauIdentifiant().getChamp2().addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) { }

            @Override
            public void keyPressed(KeyEvent e) { }

            @Override
            public void keyReleased(KeyEvent e) { checkIdentifiant(); }
        });
        
        panneauFormInscription1.getPanneauCourriel().getChamp2().getDocument().addDocumentListener(new Helpers.SimpleDocumentListener() {
            @Override
            public void update(DocumentEvent e) {
                checkEmail();
            }
        });
        
        panneauFormInscription1.getPanneauCourriel().getChamp2().addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) { }

            @Override
            public void keyPressed(KeyEvent e) { }

            @Override
            public void keyReleased(KeyEvent e) { checkEmail(); }
        });
        
    }
    
    private void checkIdentifiant(){
        List<Map<String, Object>> user = null;
                
        try {
            user = Helpers.getIntance().getUtilisateur(panneauFormInscription1.getPanneauIdentifiant().getChamp2().getText());
        } catch (SQLException ex) {
            Logger.getLogger(Inscription.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(user == null || user.size() < 0){
            panneauFormInscription1.getPanneauIdentifiant().getjLabelEtatChamp().setText("Identifiant disponible !");
            panneauFormInscription1.getPanneauIdentifiant().getjLabelEtatChamp().setForeground(Reference.COLOR_VALIDATED);
            panneauFormInscription1.setIdentifiantOK(true);
        }else{
            panneauFormInscription1.getPanneauIdentifiant().getjLabelEtatChamp().setText("Utilisateur déjà existant !");
            panneauFormInscription1.getPanneauIdentifiant().getjLabelEtatChamp().setForeground(Reference.COLOR_NOT_VALIDATED);
            panneauFormInscription1.setIdentifiantOK(false);
        }
    }
    
    private void checkEmail(){
        List<Map<String, Object>> user = null;
                
        try {
            user = Helpers.getIntance().getUtilisateur(panneauFormInscription1.getPanneauCourriel().getChamp2().getText());
        } catch (SQLException ex) {
            Logger.getLogger(Inscription.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(user == null || user.size() < 0){
            panneauFormInscription1.getPanneauCourriel().getjLabelEtatChamp().setText("Email disponible !");
            panneauFormInscription1.getPanneauCourriel().getjLabelEtatChamp().setForeground(Reference.COLOR_VALIDATED);
            panneauFormInscription1.setCourrielOK(true);
        }else{
            panneauFormInscription1.getPanneauCourriel().getjLabelEtatChamp().setText("Email déjà existant !");
            panneauFormInscription1.getPanneauCourriel().getjLabelEtatChamp().setForeground(Reference.COLOR_NOT_VALIDATED);
            panneauFormInscription1.setCourrielOK(false);
        }
    }

    public PanneauFormInscription getPanneauFormInscription1() {
        return panneauFormInscription1;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitleAPI;
    private fr.karim.main.auth.JPanelAuthWithAPI jPanelAuthWithAPI1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private com.karimandco.auth.PanneauFormInscription panneauFormInscription1;
    // End of variables declaration//GEN-END:variables
}
