/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.karim.main.composant;

import fr.karim.main.utils.Helpers;
import fr.karim.main.utils.user.CentreInteret;
import fr.karim.main.utils.user.Informatique;
import fr.karim.main.utils.user.Langue;
import fr.karim.references.Message;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karim
 */
public class JPanelComplementaire extends javax.swing.JPanel {

    private List<CentreInteret> arrayCentreInteret = new ArrayList<CentreInteret>();
    private List<Informatique> arrayInformatique = new ArrayList<Informatique>();
    private List<Langue> arrayLangue = new ArrayList<Langue>();
    
    private DefaultTableModel jTableCentreInteretModel;
    private DefaultTableModel jTableInformatiqueModel;
    private DefaultTableModel jTableLangueModel;
    
    /**
     * Creates new form Complementaire
     */
    public JPanelComplementaire() {
        initComponents();
        
        jTextAreaDescription.setLineWrap(true);
        
        init();
    }
    
    public void init(){
                
        Helpers.setPlaceholder(jTextFieldLabel, "Titre");
        Helpers.setPlaceholder(jTextAreaDescription, "Description");
        
        Helpers.setPlaceholder(jTextFieldLangue, "Langue");
        Helpers.setPlaceholder(jTextFieldNiveau, "Ex: lu, parler, ecrit ...");
        
        for( Object i : new Object[]{jTableInformatique, jTableCentreInteret} ){
            JTable t = (JTable) i;
            t.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String [] {
                    "Label", "Description"
                }
            ));
        }
        
        jTableLangue.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String [] {
                "Label", "Niveau", "(%)"
            }
        ));
        
        jTableCentreInteretModel = (DefaultTableModel) jTableCentreInteret.getModel();
        jTableInformatiqueModel = (DefaultTableModel) jTableInformatique.getModel();
        jTableLangueModel = (DefaultTableModel) jTableLangue.getModel();
    }

    public List<CentreInteret> getArrayCentreInteret() {
        return arrayCentreInteret;
    }

    public void setArrayCentreInteret(List<CentreInteret> arrayCentreInteret) {
        this.arrayCentreInteret = arrayCentreInteret;
    }

    public List<Informatique> getArrayInformatique() {
        return arrayInformatique;
    }

    public void setArrayInformatique(List<Informatique> arrayInformatique) {
        this.arrayInformatique = arrayInformatique;
    }

    public List<Langue> getArrayLangue() {
        return arrayLangue;
    }

    public void setArrayLangue(List<Langue> arrayLangue) {
        this.arrayLangue = arrayLangue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonAjout = new javax.swing.JButton();
        jButtonSuppr = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldLabel = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jComboBoxMode = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableLangue = new javax.swing.JTable();
        jTextFieldNiveau = new javax.swing.JTextField();
        jButtonSupprLangue = new javax.swing.JButton();
        jButtonAjoutLangue = new javax.swing.JButton();
        jTextFieldLangue = new javax.swing.JTextField();
        jSpinnerPercentage = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableInformatique = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableCentreInteret = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(78, 39, 123));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Centre d'intêrets");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAjout.setText("Ajouter");
        jButtonAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjoutActionPerformed(evt);
            }
        });

        jButtonSuppr.setText("Supprimer");
        jButtonSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(78, 39, 123));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Informatiques");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDescription);

        jComboBoxMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centre d'intêrets", "Informatiques" }));

        jPanel3.setBackground(new java.awt.Color(78, 39, 123));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Langues");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableLangue.setModel(new javax.swing.table.DefaultTableModel());
        jScrollPane3.setViewportView(jTableLangue);

        jButtonSupprLangue.setText("Supprimer");
        jButtonSupprLangue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprLangueActionPerformed(evt);
            }
        });

        jButtonAjoutLangue.setText("Ajouter");
        jButtonAjoutLangue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjoutLangueActionPerformed(evt);
            }
        });

        jSpinnerPercentage.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        jLabel3.setText("%");

        jTableInformatique.setModel(new javax.swing.table.DefaultTableModel());
        jScrollPane4.setViewportView(jTableInformatique);

        jTableCentreInteret.setModel(new javax.swing.table.DefaultTableModel());
        jScrollPane5.setViewportView(jTableCentreInteret);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxMode, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonSuppr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAjout))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonSupprLangue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAjoutLangue))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldLangue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNiveau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSuppr)
                    .addComponent(jButtonAjout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNiveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLangue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSupprLangue)
                    .addComponent(jButtonAjoutLangue))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjoutActionPerformed
        
        // ajouter les info dans l'un des tableaux
        // possibilité : "Centre d'intêrets", "Informatiques"
        
        String selected = String.valueOf(jComboBoxMode.getSelectedItem());
        
        if(!jTextFieldLabel.getText().equals("") && !jTextFieldLabel.getText().equals("Titre")){
            if(selected != null && selected.equals("Centre d'intêrets")){
                arrayCentreInteret.add(
                        new CentreInteret()
                        .setLabel(jTextFieldLabel.getText())
                        .setDescription(jTextAreaDescription.getText().equals("Description") ? "" : jTextAreaDescription.getText())
                );
                jTableCentreInteret.removeAll();
                jTableCentreInteretModel.setRowCount(0);
                for(CentreInteret i : arrayCentreInteret){
                    jTableCentreInteretModel.addRow(new Object[]{ i.getLabel(), i.getDescription() });
                }
                
                jTableCentreInteret.setModel(jTableCentreInteretModel);
                
            }else{
                arrayInformatique.add(
                    new Informatique()
                    .setLabel(jTextFieldLabel.getText())
                    .setDescription(jTextAreaDescription.getText().equals("Description") ? "" : jTextAreaDescription.getText())
                );
                
                jTableInformatique.removeAll();
                jTableInformatiqueModel.setRowCount(0);
                for(Informatique i : arrayInformatique){
                    jTableInformatiqueModel.addRow(new Object[]{ i.getLabel(), i.getDescription() });
                }
                
                jTableInformatique.setModel(jTableInformatiqueModel);
            }
        }else{
            JOptionPane.showMessageDialog(this, 
                    String.format(Message.MESSAGE_CI_INFO, selected),
                    String.format(Message.TITRE_MESSAGE_CI_INFO, selected), JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonAjoutActionPerformed

    private void jButtonSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprActionPerformed
        
        String selected = String.valueOf(jComboBoxMode.getSelectedItem());

        
        int reply = JOptionPane.showConfirmDialog(null, 
                String.format(Message.QUESTION_SUPPRESION, "ce" + selected + ".\nAttention ! vous êtes cela va le supprimer dans l'interface mais aussi dans la base de donnée"), 
                Message.TITLE_QUESTION_SUPPRESION, JOptionPane.YES_NO_OPTION);
        
        if (reply == JOptionPane.YES_OPTION) {
            if(selected != null && selected.equals("Centre d'intêrets")){

                int[] i = jTableCentreInteret.getSelectedRows();

                if(i != null && i.length > 0) {
                    for (int j = i.length - 1; j >= 0; j--) {
                        
                        CentreInteret centreinteret = arrayCentreInteret.get(i[j]);
                        if(centreinteret.getId() != null){
                            centreinteret.delete();
                        }
                        
                        arrayCentreInteret.remove(i[j]);
                        jTableCentreInteretModel.removeRow(i[j]);
                    }
                    jTableCentreInteret.setModel(jTableCentreInteretModel);
                }else{
                    JOptionPane.showMessageDialog(this, 
                        String.format(Message.MESSAGE_CI_INFO_DELETE, selected),
                        Message.TITRE_MESSAGE_CI_INFO_DELETE, JOptionPane.WARNING_MESSAGE);
                }

            }else{

                int[] i = jTableInformatique.getSelectedRows();

                if(i != null && i.length > 0) {
                    for (int j = i.length - 1; j >= 0; j--) {
                        
                        Informatique informatique = arrayInformatique.get(i[j]);
                        if(informatique.getId() != null){
                            informatique.delete();
                        }
                        
                        arrayInformatique.remove(i[j]);
                        jTableInformatiqueModel.removeRow(i[j]);
                    }
                    jTableInformatique.setModel(jTableInformatiqueModel);
                }else{
                    JOptionPane.showMessageDialog(this, 
                        String.format(Message.MESSAGE_CI_INFO, selected),
                        String.format(Message.TITRE_MESSAGE_CI_INFO, selected), JOptionPane.WARNING_MESSAGE);
                }

            }
        }
        
    }//GEN-LAST:event_jButtonSupprActionPerformed

    private void jButtonSupprLangueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprLangueActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, 
                String.format(Message.QUESTION_SUPPRESION, "cette maitrise de langue.\nAttention ! vous êtes cela va le supprimer dans l'interface mais aussi dans la base de donnée"), 
                Message.TITLE_QUESTION_SUPPRESION, JOptionPane.YES_NO_OPTION);
        
        if (reply == JOptionPane.YES_OPTION) {
            int[] i = jTableLangue.getSelectedRows();
            
            if(i != null && i.length > 0) {
                for (int j = i.length - 1; j >= 0; j--) {
                    
                    Langue langue = arrayLangue.get(i[j]);
                    if(langue.getId() != null){
                        langue.delete();
                    }
                    
                    arrayLangue.remove(i[j]);
                    jTableLangueModel.removeRow(i[j]);
                }
                jTableLangue.setModel(jTableLangueModel);
            }else{
                JOptionPane.showMessageDialog(this, 
                    String.format(Message.MESSAGE_CI_INFO_DELETE, "Langue"),
                    Message.TITRE_MESSAGE_CI_INFO_DELETE, JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonSupprLangueActionPerformed

    private void jButtonAjoutLangueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjoutLangueActionPerformed
        if(!jTextFieldLangue.getText().equals("") && !jTextFieldLangue.getText().equals("Langue")){
            arrayLangue.add(
                    new Langue()
                    .setLabel(jTextFieldLangue.getText())
                    .setNiveau(jTextFieldNiveau.getText().equals("Ex: lu, parler, ecrit ...") ? "" : jTextFieldNiveau.getText())
                    .setPercentage((Integer) jSpinnerPercentage.getValue())
            );
            jTableLangue.removeAll();
            jTableLangueModel.setRowCount(0);
            for(Langue i : arrayLangue){
                jTableLangueModel.addRow(new Object[]{ i.getLabel(), i.getNiveau(), i.getPercentage() });
            }

            jTableLangue.setModel(jTableLangueModel);
                
        }else{
            JOptionPane.showMessageDialog(this, 
                String.format(Message.MESSAGE_CI_INFO, "Langue"),
                String.format(Message.TITRE_MESSAGE_CI_INFO, "Langue"), JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAjoutLangueActionPerformed

    public void sync(){
        this.sync(null);
    }
    
    public void sync(Integer id_utilisateur){
        
        if(arrayCentreInteret != null && arrayCentreInteret.size() > 0){
            for(CentreInteret i : arrayCentreInteret){
                if(id_utilisateur != null){
                    i.setId_utilisateur(id_utilisateur);
                }
                i.sync();
            }
        }
        
        if(arrayInformatique != null && arrayInformatique.size() > 0){
            for(Informatique i : arrayInformatique){
                if(id_utilisateur != null){
                    i.setId_utilisateur(id_utilisateur);
                }
                i.sync();
            }
        }
        
        if(arrayLangue != null && arrayLangue.size() > 0){
            for(Langue i : arrayLangue){
                if(id_utilisateur != null){
                    i.setId_utilisateur(id_utilisateur);
                }
                i.sync();
            }
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjout;
    private javax.swing.JButton jButtonAjoutLangue;
    private javax.swing.JButton jButtonSuppr;
    private javax.swing.JButton jButtonSupprLangue;
    private javax.swing.JComboBox<String> jComboBoxMode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinnerPercentage;
    private javax.swing.JTable jTableCentreInteret;
    private javax.swing.JTable jTableInformatique;
    private javax.swing.JTable jTableLangue;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextFieldLabel;
    private javax.swing.JTextField jTextFieldLangue;
    private javax.swing.JTextField jTextFieldNiveau;
    // End of variables declaration//GEN-END:variables
}
