/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.karim.main;

import com.alee.utils.swing.extensions.WindowCloseAdapter;
import fr.karim.main.utils.user.Utilisateur;
import fr.karim.references.Message;
import fr.karim.references.Reference;

import java.awt.event.ComponentEvent;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author karim
 */
public class JFrameSoftware extends javax.swing.JFrame {
    
    javax.swing.JMenu jMenuAdmin = new javax.swing.JMenu();
    javax.swing.JMenuItem jMenuItemGestionUser = new javax.swing.JMenuItem();
    
    JDialogAdministration administrationDialog = null;
    JDialogAccount accountDialog = null;
    
    /**
     * Creates new form JFrameSoftware
     */
    public JFrameSoftware() {
        initComponents();
        
        init();
    }
    
    private void init(){
        if(Utilisateur.getInstance().getEstConnecte()){
            if(Utilisateur.getInstance().getStatut() != null && Utilisateur.getInstance().isAdmin()){
                
                jMenuAdmin.setText("Administration");

                // Code of sub-components and layout - not shown here

                jMenuItemGestionUser.setText("Gestions utilisateurs");

                jMenuItemGestionUser.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        openAdmin();
                    }
                });
                jMenuAdmin.add(jMenuItemGestionUser);
                jMenuBarSoftware.add(jMenuAdmin);
            }
        }
        
    }

    public JMenuItem getjMenuItemGestionUser() {
        return jMenuItemGestionUser;
    }
    
    private void openAdmin(){
        
        administrationDialog = new JDialogAdministration(this, rootPaneCheckingEnabled);
        administrationDialog.setTitle(String.format(Reference.TITLE_NAME_SOFTWARE, "Administration"));
        administrationDialog.setModal(true);
        administrationDialog.setVisible(true);
        
        administrationDialog.addWindowListener(new WindowCloseAdapter() {
            @Override
            public void closed(ComponentEvent ce) {
                administrationDialog.setModal(false);
                administrationDialog.setVisible(false);
                administrationDialog = null;

            }
        });
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        software1 = new fr.karim.main.composant.Software();
        jMenuBarSoftware = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemFile_Accueil = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemCV_List = new javax.swing.JMenuItem();
        jMenuItemCV_Create = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemImportExport = new javax.swing.JMenuItem();
        jMenuItemAccount = new javax.swing.JMenuItem();
        jMenuItemLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jMenuItemFile_Accueil.setText("Acceuil");
        jMenuItemFile_Accueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFile_AccueilActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemFile_Accueil);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExit);

        jMenuBarSoftware.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBarSoftware.add(jMenu2);

        jMenu3.setText("Curriculum Vitae");

        jMenuItemCV_List.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCV_List.setText("Liste");
        jMenuItemCV_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCV_ListActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemCV_List);

        jMenuItemCV_Create.setText("Création");
        jMenuItemCV_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCV_CreateActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemCV_Create);

        jMenuBarSoftware.add(jMenu3);

        jMenu4.setText("Utilisateur");

        jMenuItemImportExport.setText("Importer/Exporter");
        jMenuItemImportExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImportExportActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemImportExport);

        jMenuItemAccount.setText("Mon Compte");
        jMenuItemAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAccountActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemAccount);

        jMenuItemLogout.setText("Deconnexion");
        jMenu4.add(jMenuItemLogout);

        jMenuBarSoftware.add(jMenu4);

        setJMenuBar(jMenuBarSoftware);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(software1, javax.swing.GroupLayout.DEFAULT_SIZE, 1172, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(software1, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCV_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCV_ListActionPerformed
        software1.handlePanel("panel_list_cv");
    }//GEN-LAST:event_jMenuItemCV_ListActionPerformed

    private void jMenuItemFile_AccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFile_AccueilActionPerformed
        software1.handlePanel("panel_acceuil");
    }//GEN-LAST:event_jMenuItemFile_AccueilActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemCV_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCV_CreateActionPerformed
        software1.handlePanel("panel_create_cv");
    }//GEN-LAST:event_jMenuItemCV_CreateActionPerformed

    private void jMenuItemImportExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImportExportActionPerformed
        software1.handlePanel("panel_import_export");
    }//GEN-LAST:event_jMenuItemImportExportActionPerformed

    private void jMenuItemAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAccountActionPerformed
        if(Utilisateur.getInstance().getEstConnecte()){
            accountDialog = new JDialogAccount(this, rootPaneCheckingEnabled);
            accountDialog.setTitle(String.format(Reference.TITLE_NAME_SOFTWARE, "Mon compte"));
            accountDialog.setModal(true);
            accountDialog.setVisible(true);

            accountDialog.addWindowListener(new WindowCloseAdapter() {
                @Override
                public void closed(ComponentEvent ce) {
                    accountDialog.setModal(false);
                    accountDialog.setVisible(false);
                    accountDialog = null;
                }
            });
        }else{
            JOptionPane.showMessageDialog(this, Message.MESSAGE_NOT_CONNECT, Message.TITLE_MESSAGE_NOT_CONNECT, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameSoftware().setVisible(true);
            }
        });
    }

    public JMenuItem getjMenuItemLogout() {
        return jMenuItemLogout;
    }

    public void setjMenuItemLogout(JMenuItem jMenuItemLogout) {
        this.jMenuItemLogout = jMenuItemLogout;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBarSoftware;
    private javax.swing.JMenuItem jMenuItemAccount;
    private javax.swing.JMenuItem jMenuItemCV_Create;
    private javax.swing.JMenuItem jMenuItemCV_List;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemFile_Accueil;
    private javax.swing.JMenuItem jMenuItemImportExport;
    private javax.swing.JMenuItem jMenuItemLogout;
    private fr.karim.main.composant.Software software1;
    // End of variables declaration//GEN-END:variables
}
