/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.karimandco.auth;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Damien F, Pawel R, Théo M
 */
public class PanneauChampSecret extends javax.swing.JPanel {

    /**
     * Creates new form PanneauChampSecret
     */
    public PanneauChampSecret() {
        initComponents();
        
        this.setBackground(new Color(25, 28, 32));
        jLabelNomChampSecret.setForeground(Color.WHITE);
        // champ2.setBackground(new Color(0,0,0,0));
        // note colore : 214,217,223
        champSecret1.setBackground(this.getBackground());
        champSecret1.setForeground(Color.WHITE);
        champSecret1.setCaretColor(Color.WHITE);
        
        jLabelEtatChampSecret.setBackground(new Color(25, 28, 32));
        
        jSeparator1.setBackground(Color.WHITE);
        jSeparator1.setForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        champSecret1 = new com.karimandco.auth.ChampSecret();
        jLabelEtatChampSecret = new javax.swing.JLabel();
        jLabelNomChampSecret = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        champSecret1.setEditable(false);
        champSecret1.setBorder(null);
        champSecret1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabelEtatChampSecret.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelNomChampSecret.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomChampSecret.setText("champSecret");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(champSecret1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jLabelNomChampSecret, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
            .addComponent(jLabelEtatChampSecret, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabelNomChampSecret, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(champSecret1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelEtatChampSecret, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    public ChampSecret getChampSecret1() {
        return champSecret1;
    }

    public void setChampSecret1(ChampSecret champSecret1) {
        this.champSecret1 = champSecret1;
    }

    public JLabel getjLabelEtatChampSecret() {
        return jLabelEtatChampSecret;
    }

    public void setjLabelEtatChampSecret(JLabel jLabelEtatChampSecret) {
        this.jLabelEtatChampSecret = jLabelEtatChampSecret;
    }

    public void setjLabelEtatChampSecret(String nom) {
        this.jLabelEtatChampSecret.setText(nom);
    }

    public void setjLabelEtatChampSecret(Color couleur) {
        this.jLabelEtatChampSecret.setForeground(couleur);
    }

    public JLabel getjLabelNomChampSecret() {
        return jLabelNomChampSecret;
    }

    public void setjLabelNomChampSecret(JLabel jLabelNomChampSecret) {
        this.jLabelNomChampSecret = jLabelNomChampSecret;
    }

    public void setjLabelNomChampSecret(String nom) {
        this.jLabelNomChampSecret.setText(nom);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.karimandco.auth.ChampSecret champSecret1;
    private javax.swing.JLabel jLabelEtatChampSecret;
    private javax.swing.JLabel jLabelNomChampSecret;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
