/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.karimandco.auth;

import fr.karim.references.Reference;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JSeparator;

/**
 *
 * @author Damien F, Pawel R, Théo M
 */
public class PanneauChamp extends javax.swing.JPanel {

    /**
     * Creates new form PanneauChampSecret
     */
    public PanneauChamp() {
        initComponents();
        
        this.setBackground(Reference.MAIN_DARK);
        jLabelNomChamp.setForeground(Color.WHITE);
        // champ2.setBackground(new Color(0,0,0,0));
        // note colore : 214,217,223
        champ2.setBackground(this.getBackground());
        champ2.setCaretColor(Color.WHITE);
        
        jLabelEtatChamp.setBackground(Reference.MAIN_DARK);
        
        jSeparator1.setBackground(Color.WHITE);
        jSeparator1.setForeground(Color.WHITE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEtatChamp = new javax.swing.JLabel();
        jLabelNomChamp = new javax.swing.JLabel();
        champ2 = new com.karimandco.auth.Champ();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabelEtatChamp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelNomChamp.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabelNomChamp.setForeground(new java.awt.Color(25, 28, 32));
        jLabelNomChamp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomChamp.setText("champ");

        champ2.setBorder(null);
        champ2.setForeground(new java.awt.Color(255, 255, 255));
        champ2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNomChamp, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(champ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEtatChamp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelNomChamp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(champ2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelEtatChamp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    public Champ getChamp2() {
        return champ2;
    }

    public void setChamp2(Champ champ2) {
        this.champ2 = champ2;
    }

    public JLabel getjLabelEtatChamp() {
        return jLabelEtatChamp;
    }

    public void setjLabelEtatChamp(JLabel jLabelEtatChamp) {
        this.jLabelEtatChamp = jLabelEtatChamp;
    }

    public void setjLabelEtatChamp(String nom) {
        this.jLabelEtatChamp.setText(nom);
    }

    public void setjLabelEtatChamp(Color couleur) {
        this.jLabelEtatChamp.setForeground(couleur);
    }

    public JLabel getjLabelNomChamp() {
        return jLabelNomChamp;
    }

    public void setjLabelNomChamp(JLabel jLabelNomChamp) {
        this.jLabelNomChamp = jLabelNomChamp;
    }

    public void setjLabelNomChamp(String nom) {
        this.jLabelNomChamp.setText(nom);
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.karimandco.auth.Champ champ2;
    private javax.swing.JLabel jLabelEtatChamp;
    private javax.swing.JLabel jLabelNomChamp;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
