/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.karim.main.auth;

import fr.karim.main.auth.facebook.JPanelFacebook;
import fr.karim.main.auth.google.JPanelGoogle;
import fr.karim.main.auth.facebook.CustomUserFacebook;
import fr.karim.main.auth.google.CustomUserGoogle;

/**
 *
 * @author karim
 */
public class JPanelAuthWithAPI extends javax.swing.JPanel {

    /**
     * Creates new form AuthWithAPI
     */
    public JPanelAuthWithAPI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFacebook1 = new fr.karim.main.auth.facebook.JPanelFacebook();
        jPanelGoogle1 = new fr.karim.main.auth.google.JPanelGoogle();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelGoogle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFacebook1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelGoogle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelFacebook1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public CustomUserFacebook getUserOAuthFacebook() {
        return jPanelFacebook1.getUserOAuth();
    }
    
    public CustomUserGoogle getUserOAuthGoogle(){
        return jPanelGoogle1.getUserOAuth();
    }

    public JPanelFacebook getjPanelFacebook1() {
        return jPanelFacebook1;
    }

    public void setjPanelFacebook1(JPanelFacebook jPanelFacebook1) {
        this.jPanelFacebook1 = jPanelFacebook1;
    }

    public JPanelGoogle getjPanelGoogle1() {
        return jPanelGoogle1;
    }

    public void setjPanelGoogle1(JPanelGoogle jPanelGoogle1) {
        this.jPanelGoogle1 = jPanelGoogle1;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fr.karim.main.auth.facebook.JPanelFacebook jPanelFacebook1;
    private fr.karim.main.auth.google.JPanelGoogle jPanelGoogle1;
    // End of variables declaration//GEN-END:variables
}
